### ISSUE TITLE
No mention of automaticly creating setters and gettors

### ISSUE THREAD

**Issue by Anthonyntilelli** [learn-co-curriculum/ruby-object-attrs-readme#39]
Ruby has the ability to automatically create setters and getters 

`attr_reader` creates only the reader.
`attr_writer` creates only the writer.
`attr_accessor` creates both 

https://www.rubyguides.com/2018/11/attr_accessor/

**Comment by sgharms** [comment]
We've consciously not mentioned those here because they are rather "magical" and confuse the issue between:

method called `some_variable=(arg)`
method called `some_variable`
and the actual variable that both of those wrap `@some_variable`

We _do_ cover these macros in: `ruby-oo-macros-readme`. We'll put in a link to set up that these ideas are taught later.

Thanks for your feedback!
